import type { DispatchState, Experiment, ModelCapabilityProbe, Opportunity, QueueItem } from "../common/types.js";
import { buildDefaultModelProbe } from "../runtime-model/index.js";

const RECOVERY_SWEEP_MINUTES = 3;
const HEARTBEAT_MINUTES = 12;
const LOCK_TTL_MINUTES = 15;

const DEFAULT_CONCURRENCY_LIMITS: DispatchState["agentConcurrencyLimits"] = {
  ceo: 1,
  research: 1,
  builder: 1,
  distribution: 1,
  treasury: 1,
  skillsmith: 1,
  ops: 2,
};

function sortQueue(queue: QueueItem[]): QueueItem[] {
  return [...queue].sort((left, right) => {
    if (right.priority !== left.priority) {
      return right.priority - left.priority;
    }

    return new Date(left.dueAt).getTime() - new Date(right.dueAt).getTime();
  });
}

function isoNow(): string {
  return new Date().toISOString();
}

function toDueNow(task: QueueItem, notePrefix: string): QueueItem {
  return {
    ...task,
    dueAt: isoNow(),
    notes: `${notePrefix} ${task.notes}`.trim(),
  };
}

function pickFallbackTask(opportunities: Opportunity[], experiments: Experiment[], queue: QueueItem[]): QueueItem | null {
  if (queue.length > 0) {
    return toDueNow(queue[0]!, "[idle-prevention]");
  }

  const topExperiment = experiments[0];
  if (topExperiment?.nextActions[0]) {
    return toDueNow(topExperiment.nextActions[0], "[experiment-continuation]");
  }

  const topOpportunity = opportunities[0];
  if (!topOpportunity) {
    return null;
  }

  return {
    id: `${topOpportunity.id}-fallback-research`,
    title: `Refresh next-best-action research for ${topOpportunity.title}`,
    owner: "research",
    initiativeId: topOpportunity.id,
    reason: "new-opportunity-research",
    priority: 70,
    dueAt: isoNow(),
    notes: "Generated by idle prevention because no ready task was available.",
  };
}

function chooseContinuationOwner(owner: QueueItem["owner"]): QueueItem["owner"] | null {
  switch (owner) {
    case "ceo":
      return "builder";
    case "builder":
      return "distribution";
    case "distribution":
      return "treasury";
    case "treasury":
      return "ceo";
    case "research":
      return "ceo";
    case "skillsmith":
      return "ops";
    case "ops":
      return "ceo";
    default:
      return null;
  }
}

function promoteContinuation(queue: QueueItem[], completedTaskId: string): QueueItem[] {
  const completedTask = queue.find((task) => task.id === completedTaskId);
  if (!completedTask) {
    return queue.filter((task) => task.id !== completedTaskId);
  }

  const remaining = queue.filter((task) => task.id !== completedTaskId);
  const preferredOwner = chooseContinuationOwner(completedTask.owner);
  const sameInitiative = remaining.filter((task) => task.initiativeId === completedTask.initiativeId);
  const nextTask =
    sameInitiative.find((task) => task.owner === preferredOwner) ??
    sameInitiative.sort((left, right) => right.priority - left.priority)[0];

  if (!nextTask) {
    return remaining;
  }

  return remaining.map((task) =>
    task.id === nextTask.id
      ? toDueNow(task, `[continuation-from:${completedTask.id}]`)
      : task,
  );
}

function readyQueue(queue: QueueItem[]): QueueItem[] {
  const now = Date.now();
  return sortQueue(
    queue.filter(
      (task) =>
        new Date(task.dueAt).getTime() <= now + 24 * 60 * 60 * 1000 ||
        task.priority >= 70,
    ),
  );
}

function dedupeQueue(queue: QueueItem[]): QueueItem[] {
  const deduped = new Map<string, QueueItem>();

  for (const task of sortQueue(queue)) {
    if (!deduped.has(task.id)) {
      deduped.set(task.id, task);
    }
  }

  return Array.from(deduped.values());
}

function recoverLocks(
  previousLocks: DispatchState["locks"],
): { activeLocks: DispatchState["locks"]; recoveryActions: string[] } {
  const now = Date.now();
  const activeLocks: DispatchState["locks"] = [];
  const recoveryActions: string[] = [];

  for (const lock of previousLocks) {
    if (new Date(lock.expiresAt).getTime() < now) {
      recoveryActions.push(`Recovered stale lock for ${lock.taskId} owned by ${lock.owner}.`);
      continue;
    }

    activeLocks.push(lock);
  }

  return { activeLocks, recoveryActions };
}

function buildRecoveryActions(queue: QueueItem[], blockedInitiativeIds: string[]): string[] {
  const now = Date.now();
  const overdue = queue.filter((task) => new Date(task.dueAt).getTime() < now - 2 * 60 * 60 * 1000);
  const actions = overdue.map(
    (task) => `Requeue overdue task ${task.id} owned by ${task.owner}; it is more than two hours late.`,
  );

  for (const blockedInitiativeId of blockedInitiativeIds) {
    actions.push(`Initiative ${blockedInitiativeId} is blocked; other initiatives should continue normally.`);
  }

  if (queue.length === 0) {
    actions.push("Ready queue is empty; generate a fallback task immediately.");
  }

  return actions;
}

function lockCountByOwner(previousLocks: DispatchState["locks"]): Map<QueueItem["owner"], number> {
  const counts = new Map<QueueItem["owner"], number>();
  for (const lock of previousLocks) {
    counts.set(lock.owner, (counts.get(lock.owner) ?? 0) + 1);
  }
  return counts;
}

function deriveConcurrencyLimits(
  queue: QueueItem[],
  previousState: DispatchState | null | undefined,
  modelProbe: ModelCapabilityProbe,
): DispatchState["agentConcurrencyLimits"] {
  const limits = { ...DEFAULT_CONCURRENCY_LIMITS };
  const queueDepth = queue.length;
  const recentRecoveries = previousState?.recoveryActions.length ?? 0;
  const driftPenalty = modelProbe.drift.length > 3 ? 1 : 0;

  if (queueDepth >= 6) {
    limits.research += 1;
    limits.builder += 1;
    limits.distribution += 1;
    limits.skillsmith += 1;
    limits.ops += 1;
  }

  if (queueDepth >= 12) {
    limits.builder += 1;
    limits.distribution += 1;
    limits.ops += 1;
  }

  if (recentRecoveries >= 6 || driftPenalty > 0) {
    limits.builder = Math.max(1, limits.builder - driftPenalty);
    limits.distribution = Math.max(1, limits.distribution - driftPenalty);
    limits.research = Math.max(1, limits.research - driftPenalty);
  }

  return limits;
}

function selectAssignments(
  ready: QueueItem[],
  activeLocks: DispatchState["locks"],
  limits: DispatchState["agentConcurrencyLimits"],
): QueueItem[] {
  const used = lockCountByOwner(activeLocks);
  const selected: QueueItem[] = [];
  const selectedByOwner = new Map<QueueItem["owner"], number>();

  for (const task of ready) {
    const owner = task.owner;
    const usedSlots = used.get(owner) ?? 0;
    const newlySelected = selectedByOwner.get(owner) ?? 0;
    if (usedSlots + newlySelected >= limits[owner]) {
      continue;
    }

    selected.push(task);
    selectedByOwner.set(owner, newlySelected + 1);
  }

  return selected;
}

function buildActiveAssignments(
  queue: QueueItem[],
  locks: DispatchState["locks"],
): DispatchState["activeAssignments"] {
  return locks
    .map((lock) => {
      const task = queue.find((candidate) => candidate.id === lock.taskId);
      if (!task) {
        return null;
      }

      return {
        taskId: task.id,
        owner: task.owner,
        initiativeId: task.initiativeId,
        title: task.title,
        acquiredAt: lock.acquiredAt,
        expiresAt: lock.expiresAt,
      };
    })
    .filter((assignment): assignment is DispatchState["activeAssignments"][number] => Boolean(assignment))
    .sort((left, right) => left.owner.localeCompare(right.owner) || left.taskId.localeCompare(right.taskId));
}

export function buildDispatchState(options: {
  opportunities: Opportunity[];
  experiments: Experiment[];
  queue: QueueItem[];
  previousState?: DispatchState | null;
  completedTaskId?: string;
  blockedInitiativeIds?: string[];
  modelProbe?: ModelCapabilityProbe;
}): DispatchState {
  const completedTaskIds = new Set(options.previousState?.completedTaskIds ?? []);
  let queue = dedupeQueue(options.queue);
  const blockedInitiativeIds = options.blockedInitiativeIds ?? options.previousState?.blockedInitiativeIds ?? [];
  const recoveredLocks = recoverLocks(options.previousState?.locks ?? []);
  let activeLocks = recoveredLocks.activeLocks;
  const modelProbe = options.modelProbe ?? buildDefaultModelProbe();
  const concurrencyLimits = deriveConcurrencyLimits(queue, options.previousState, modelProbe);

  if (options.completedTaskId) {
    completedTaskIds.add(options.completedTaskId);
    queue = promoteContinuation(queue, options.completedTaskId);
    activeLocks = activeLocks.filter((lock) => lock.taskId !== options.completedTaskId);
  }

  queue = queue.filter((task) => !completedTaskIds.has(task.id));

  const currentLockCountByOwner = lockCountByOwner(activeLocks);

  let ready = readyQueue(
    queue.filter(
      (task) =>
        !blockedInitiativeIds.includes(task.initiativeId) &&
        !activeLocks.some((lock) => lock.taskId === task.id) &&
        (currentLockCountByOwner.get(task.owner) ?? 0) < concurrencyLimits[task.owner],
    ),
  );
  if (ready.length === 0) {
    const fallback = pickFallbackTask(options.opportunities, options.experiments, queue);
    if (fallback) {
      const withoutExistingFallback = queue.filter((task) => task.id !== fallback.id);
      queue = sortQueue([fallback, ...withoutExistingFallback]);
      ready = readyQueue(
        queue.filter(
          (task) =>
            !blockedInitiativeIds.includes(task.initiativeId) &&
            !activeLocks.some((lock) => lock.taskId === task.id) &&
            (currentLockCountByOwner.get(task.owner) ?? 0) < concurrencyLimits[task.owner],
        ),
      );
    }
  }

  const selectedAssignments = selectAssignments(ready, activeLocks, concurrencyLimits);

  if (selectedAssignments.length > 0) {
    const acquiredAt = isoNow();
    const expiresAt = new Date(Date.now() + LOCK_TTL_MINUTES * 60 * 1000).toISOString();
    activeLocks = [
      ...activeLocks,
      ...selectedAssignments
        .filter((task) => !activeLocks.some((lock) => lock.taskId === task.id))
        .map((task) => ({
          taskId: task.id,
          owner: task.owner,
          acquiredAt,
          expiresAt,
        })),
    ];
  }

  const activeAssignments = buildActiveAssignments(queue, activeLocks);
  const assignmentTaskIds = new Set(activeAssignments.map((assignment) => assignment.taskId));
  const nextTask =
    queue.find((task) => assignmentTaskIds.has(task.id)) ??
    ready[0] ??
    null;
  const immediateContinuations = [
    ...queue.filter((task) => assignmentTaskIds.has(task.id) && task.id !== nextTask?.id),
    ...ready.filter((task) => !assignmentTaskIds.has(task.id) && task.id !== nextTask?.id),
  ].slice(0, 3);

  return {
    generatedAt: isoNow(),
    queue,
    readyQueue: ready,
    nextTask,
    immediateContinuations,
    activeAssignments,
    completedTaskIds: Array.from(completedTaskIds),
    blockedInitiativeIds,
    locks: activeLocks,
    agentConcurrencyLimits: concurrencyLimits,
    recoveryActions: [...recoveredLocks.recoveryActions, ...buildRecoveryActions(queue, blockedInitiativeIds)],
    cadence: {
      recoverySweepMinutes: RECOVERY_SWEEP_MINUTES,
      heartbeatMinutes: HEARTBEAT_MINUTES,
      immediateContinuation: true,
    },
    usagePolicy: {
      strategicModel: modelProbe.strategicTarget,
      openClawModel: modelProbe.openClawPrimary,
      compactionRequired: true,
    },
  };
}
