import type { DispatchState, Experiment, Opportunity, QueueItem } from "../common/types.js";
import { buildDefaultModelProbe } from "../runtime-model/index.js";

const RECOVERY_SWEEP_MINUTES = 3;
const HEARTBEAT_MINUTES = 12;

function sortQueue(queue: QueueItem[]): QueueItem[] {
  return [...queue].sort((left, right) => {
    if (right.priority !== left.priority) {
      return right.priority - left.priority;
    }

    return new Date(left.dueAt).getTime() - new Date(right.dueAt).getTime();
  });
}

function isoNow(): string {
  return new Date().toISOString();
}

function toDueNow(task: QueueItem, notePrefix: string): QueueItem {
  return {
    ...task,
    dueAt: isoNow(),
    notes: `${notePrefix} ${task.notes}`.trim(),
  };
}

function pickFallbackTask(opportunities: Opportunity[], experiments: Experiment[], queue: QueueItem[]): QueueItem | null {
  if (queue.length > 0) {
    return toDueNow(queue[0]!, "[idle-prevention]");
  }

  const topExperiment = experiments[0];
  if (topExperiment?.nextActions[0]) {
    return toDueNow(topExperiment.nextActions[0], "[experiment-continuation]");
  }

  const topOpportunity = opportunities[0];
  if (!topOpportunity) {
    return null;
  }

  return {
    id: `${topOpportunity.id}-fallback-research`,
    title: `Refresh next-best-action research for ${topOpportunity.title}`,
    owner: "research",
    initiativeId: topOpportunity.id,
    reason: "new-opportunity-research",
    priority: 70,
    dueAt: isoNow(),
    notes: "Generated by idle prevention because no ready task was available.",
  };
}

function chooseContinuationOwner(owner: QueueItem["owner"]): QueueItem["owner"] | null {
  switch (owner) {
    case "ceo":
      return "builder";
    case "builder":
      return "distribution";
    case "distribution":
      return "treasury";
    case "treasury":
      return "ceo";
    case "research":
      return "ceo";
    case "skillsmith":
      return "ops";
    case "ops":
      return "ceo";
    default:
      return null;
  }
}

function promoteContinuation(queue: QueueItem[], completedTaskId: string): QueueItem[] {
  const completedTask = queue.find((task) => task.id === completedTaskId);
  if (!completedTask) {
    return queue.filter((task) => task.id !== completedTaskId);
  }

  const remaining = queue.filter((task) => task.id !== completedTaskId);
  const preferredOwner = chooseContinuationOwner(completedTask.owner);
  const sameInitiative = remaining.filter((task) => task.initiativeId === completedTask.initiativeId);
  const nextTask =
    sameInitiative.find((task) => task.owner === preferredOwner) ??
    sameInitiative.sort((left, right) => right.priority - left.priority)[0];

  if (!nextTask) {
    return remaining;
  }

  return remaining.map((task) =>
    task.id === nextTask.id
      ? toDueNow(task, `[continuation-from:${completedTask.id}]`)
      : task,
  );
}

function readyQueue(queue: QueueItem[]): QueueItem[] {
  const now = Date.now();
  return sortQueue(
    queue.filter((task) => new Date(task.dueAt).getTime() <= now + 5 * 60 * 1000),
  );
}

function buildRecoveryActions(queue: QueueItem[]): string[] {
  const now = Date.now();
  const overdue = queue.filter((task) => new Date(task.dueAt).getTime() < now - 2 * 60 * 60 * 1000);
  const actions = overdue.map(
    (task) => `Requeue overdue task ${task.id} owned by ${task.owner}; it is more than two hours late.`,
  );

  if (queue.length === 0) {
    actions.push("Ready queue is empty; generate a fallback task immediately.");
  }

  return actions;
}

export function buildDispatchState(options: {
  opportunities: Opportunity[];
  experiments: Experiment[];
  queue: QueueItem[];
  previousState?: DispatchState | null;
  completedTaskId?: string;
}): DispatchState {
  const completedTaskIds = new Set(options.previousState?.completedTaskIds ?? []);
  let queue = sortQueue(options.queue);

  if (options.completedTaskId) {
    completedTaskIds.add(options.completedTaskId);
    queue = promoteContinuation(queue, options.completedTaskId);
  }

  queue = queue.filter((task) => !completedTaskIds.has(task.id));

  let ready = readyQueue(queue);
  if (ready.length === 0) {
    const fallback = pickFallbackTask(options.opportunities, options.experiments, queue);
    if (fallback) {
      const withoutExistingFallback = queue.filter((task) => task.id !== fallback.id);
      queue = sortQueue([fallback, ...withoutExistingFallback]);
      ready = readyQueue(queue);
    }
  }

  const modelProbe = buildDefaultModelProbe();

  return {
    generatedAt: isoNow(),
    queue,
    readyQueue: ready,
    nextTask: ready[0] ?? null,
    immediateContinuations: ready.slice(1, 3),
    completedTaskIds: Array.from(completedTaskIds),
    recoveryActions: buildRecoveryActions(queue),
    cadence: {
      recoverySweepMinutes: RECOVERY_SWEEP_MINUTES,
      heartbeatMinutes: HEARTBEAT_MINUTES,
      immediateContinuation: true,
    },
    usagePolicy: {
      strategicModel: modelProbe.strategicTarget,
      openClawModel: modelProbe.openClawPrimary,
      compactionRequired: true,
    },
  };
}
