import type { AnchorVerification, SourceRecord } from "./types.js";

export const OFFICIAL_SOURCES: SourceRecord[] = [
  {
    id: "openai-gpt-5.4-model",
    label: "OpenAI API docs: GPT-5.4 Pro",
    domain: "openai",
    url: "https://developers.openai.com/api/docs/models/gpt-5.4-pro",
    purpose: "Verify GPT-5.4 frontier positioning, model controls, and the 1.05M context window claim.",
  },
  {
    id: "openai-pro-plan",
    label: "OpenAI Help: ChatGPT Pro",
    domain: "openai",
    url: "https://help.openai.com/en/articles/9793128-what-is-chatgpt-pro",
    purpose: "Verify Pro plan GPT access wording and guardrail language.",
  },
  {
    id: "openai-business-limits",
    label: "OpenAI Help: ChatGPT Business models and limits",
    domain: "openai",
    url: "https://help.openai.com/en/articles/12003714-chatgpt-business-models-limits",
    purpose: "Verify Business plan limits and current ChatGPT model availability framing.",
  },
  {
    id: "openai-codex-plan",
    label: "OpenAI Help: Using Codex with your ChatGPT plan",
    domain: "openai",
    url: "https://help.openai.com/en/articles/11369540-using-codex-with-your-chatgpt-plan",
    purpose: "Verify Codex sign-in, plan-backed access, current usage windows, and currently advertised Codex defaults.",
  },
  {
    id: "openai-codex-upgrades",
    label: "OpenAI blog: Introducing upgrades to Codex",
    domain: "openai",
    url: "https://openai.com/index/introducing-upgrades-to-codex/",
    purpose: "Verify Codex availability surfaces and the current Codex-native model naming in public OpenAI docs.",
  },
  {
    id: "openai-codex-app",
    label: "OpenAI blog: Introducing the Codex app",
    domain: "openai",
    url: "https://openai.com/index/introducing-the-codex-app/",
    purpose: "Verify app availability, Windows support, and continuous background automation direction.",
  },
  {
    id: "openai-model-release-notes",
    label: "OpenAI Help: Model release notes",
    domain: "openai",
    url: "https://help.openai.com/en/articles/9624314-model-release-notes",
    purpose: "Verify current OpenAI model family positioning and stale-model assumptions.",
  },
  {
    id: "openclaw-model-providers",
    label: "OpenClaw docs: Model providers",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/concepts/model-providers",
    purpose: "Verify Codex OAuth support and the current public provider-model examples.",
  },
  {
    id: "openclaw-multi-agent",
    label: "OpenClaw docs: Multi-agent routing",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/concepts/multi-agent",
    purpose: "Verify per-agent isolation, workspaces, and agentDir behavior.",
  },
  {
    id: "openclaw-multiple-gateways",
    label: "OpenClaw docs: Multiple gateways",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/gateway/multiple-gateways",
    purpose: "Verify single-gateway guidance and isolation requirements.",
  },
  {
    id: "openclaw-cron-vs-heartbeat",
    label: "OpenClaw docs: Cron vs Heartbeat",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/automation/cron-vs-heartbeat",
    purpose: "Verify how heartbeat and cron should be combined.",
  },
  {
    id: "openclaw-memory",
    label: "OpenClaw docs: Memory",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/concepts/memory",
    purpose: "Verify Markdown memory, QMD support, and embedding limitations under Codex OAuth.",
  },
  {
    id: "openclaw-browser",
    label: "OpenClaw docs: Browser",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/tools/browser",
    purpose: "Verify managed browser, extension relay, headless support, and browser security posture.",
  },
  {
    id: "openclaw-browser-login",
    label: "OpenClaw docs: Browser login",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/tools/browser-login",
    purpose: "Verify attached/manual-login guidance for authenticated sites.",
  },
  {
    id: "openclaw-configuration",
    label: "OpenClaw docs: Configuration reference",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/gateway/configuration-reference",
    purpose: "Verify strict config requirements such as gateway.mode and other current startup fields.",
  },
  {
    id: "openclaw-remote-access",
    label: "OpenClaw docs: Remote access",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/guides/ssh-tunnel",
    purpose: "Verify loopback-bound gateways, Tailscale or SSH tunnel patterns, and remote control access.",
  },
  {
    id: "openclaw-nodes",
    label: "OpenClaw docs: Nodes",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/gateway/nodes/local-network",
    purpose: "Verify node-host requirements when browsers or local machines connect to a remote gateway.",
  },
  {
    id: "openclaw-secrets",
    label: "OpenClaw docs: Secrets management",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/gateway/secrets",
    purpose: "Verify SecretRef coverage and supported secret-bearing fields.",
  },
  {
    id: "openclaw-pdf",
    label: "OpenClaw docs: PDF tool",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/tools/pdf",
    purpose: "Verify first-class PDF tool availability.",
  },
  {
    id: "openclaw-security",
    label: "OpenClaw docs: Security",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/gateway/security",
    purpose: "Verify skills, plugins, and trusted-code warnings.",
  },
  {
    id: "openclaw-faq",
    label: "OpenClaw docs: FAQ",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/help/faq",
    purpose: "Verify headless browser tradeoffs and update automation guidance.",
  },
  {
    id: "openclaw-cli",
    label: "OpenClaw docs: CLI reference",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/cli",
    purpose: "Verify Node runtime guidance and CLI commands for gateway install and status.",
  },
  {
    id: "wise-security-access",
    label: "Wise docs: Security & Access",
    domain: "wise",
    url: "https://docs.wise.com/api-docs/features/authentication-access/personal-tokens",
    purpose: "Verify personal-token and OAuth 2.0 auth split plus PSD2 limitations.",
  },
  {
    id: "wise-personal-tokens",
    label: "Wise docs: Personal Tokens",
    domain: "wise",
    url: "https://docs.wise.com/api-docs/guides/personal-tokens",
    purpose: "Verify personal-token restrictions for EU or UK users.",
  },
  {
    id: "wise-getting-started",
    label: "Wise docs: Getting started",
    domain: "wise",
    url: "https://docs.wise.com/guides/developer",
    purpose: "Verify partner-credential expectations and auth guidance.",
  },
  {
    id: "steel-sessions-overview",
    label: "Steel docs: Sessions API overview",
    domain: "steel",
    url: "https://docs.steel.dev/overview/sessions-api/overview",
    purpose: "Verify session lifecycle, persistence, and browser fleet capabilities.",
  },
  {
    id: "steel-quickstart",
    label: "Steel docs: Sessions API quickstart",
    domain: "steel",
    url: "https://docs.steel.dev/overview/sessions-api/quickstart",
    purpose: "Verify session create or release flow and API key requirements.",
  },
  {
    id: "steel-profiles",
    label: "Steel docs: Profiles API overview",
    domain: "steel",
    url: "https://docs.steel.dev/overview/profiles-api/overview",
    purpose: "Verify profile-backed auth state and persistent browser profile capabilities.",
  },
  {
    id: "steel-credentials",
    label: "Steel docs: Credentials API overview",
    domain: "steel",
    url: "https://docs.steel.dev/overview/credentials-api/overview",
    purpose: "Verify Steel Cloud credential storage and injection boundaries.",
  },
  {
    id: "steel-local-vs-cloud",
    label: "Steel docs: Steel Local vs Steel Cloud",
    domain: "steel",
    url: "https://docs.steel.dev/overview/self-hosting/steel-local-vs-steel-cloud",
    purpose: "Verify current feature differences between Steel Cloud and Steel Local or self-hosted mode.",
  },
];

export const DEFAULT_ANCHOR_VERIFICATIONS: AnchorVerification[] = [
  {
    id: "anchor-1",
    anchor: "ChatGPT Pro and Business frame GPT access in ChatGPT as unlimited or effectively unlimited, subject to guardrails.",
    status: "verified",
    note: "Official Help Center docs confirm unlimited or virtually unlimited GPT access with abuse guardrails.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openai-pro-plan", "openai-business-limits"],
  },
  {
    id: "anchor-2",
    anchor: "GPT-5.4 Pro remains the frontier OpenAI model page with a 1,050,000 token context window claim.",
    status: "verified",
    note: "The current OpenAI model page documents GPT-5.4 Pro and the 1.05M context window.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openai-gpt-5.4-model"],
  },
  {
    id: "anchor-3",
    anchor: "This repo should keep GPT-5.4 as the strategic frontier target while treating Codex-surface defaults as a separately verified runtime fact.",
    status: "pending-runtime-check",
    note: "OpenAI frontier-model docs and Codex-plan docs should be evaluated separately instead of collapsed into one claim.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openai-gpt-5.4-model", "openai-codex-plan", "openai-codex-upgrades", "openai-codex-app"],
  },
  {
    id: "anchor-4",
    anchor: "OpenClaw provider examples can lag the frontier model naming, so provider-model promotion must be runtime-probed.",
    status: "verified",
    note: "OpenClaw provider docs are a compatibility source, not a guarantee that frontier model identifiers already work there.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openclaw-model-providers", "openai-gpt-5.4-model"],
  },
  {
    id: "anchor-5",
    anchor: "Codex supports ChatGPT sign-in and plan-based access.",
    status: "verified",
    note: "OpenAI Help and blog docs describe signing in with ChatGPT and included plan access.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openai-codex-plan", "openai-codex-upgrades"],
  },
  {
    id: "anchor-6",
    anchor: "Codex plan usage windows are separate from ChatGPT chat usage and require pacing discipline.",
    status: "pending-runtime-check",
    note: "Codex plan pages can change quickly, so usage-window specifics must stay tied to current official plan text.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openai-codex-plan"],
  },
  {
    id: "anchor-7",
    anchor: "OpenClaw officially supports Codex OAuth or ChatGPT sign-in for external workflows.",
    status: "verified",
    note: "OpenClaw model provider docs explicitly support Codex OAuth.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openclaw-model-providers"],
  },
  {
    id: "anchor-8",
    anchor: "OpenClaw recommends Node for stable gateways and does not recommend Bun for gateway installs.",
    status: "verified",
    note: "The CLI reference prefers Node runtime and specifically warns against Bun for stable gateways.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openclaw-cli"],
  },
  {
    id: "anchor-9",
    anchor: "The strongest always-on OpenClaw pattern is one primary loopback-bound gateway with secure remote access and remote nodes where needed.",
    status: "verified",
    note: "Current OpenClaw docs recommend one gateway for most setups, plus remote access and node-host patterns.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openclaw-multiple-gateways", "openclaw-remote-access", "openclaw-nodes"],
  },
  {
    id: "anchor-10",
    anchor: "Cron and heartbeat serve different purposes and should be combined with explicit wake or continuation flows.",
    status: "verified",
    note: "OpenClaw automation docs distinguish cron from heartbeat and keep both relevant.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openclaw-cron-vs-heartbeat", "openclaw-nodes"],
  },
  {
    id: "anchor-11",
    anchor: "OpenClaw memory is Markdown-first, and Codex OAuth does not satisfy embeddings for memory search.",
    status: "verified",
    note: "The memory docs explicitly keep Markdown as source-of-truth and separate embeddings from Codex OAuth.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openclaw-memory"],
  },
  {
    id: "anchor-12",
    anchor: "OpenClaw supports QMD and local-first memory search backends.",
    status: "verified",
    note: "The memory docs advertise experimental QMD and local embedding mode.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openclaw-memory"],
  },
  {
    id: "anchor-13",
    anchor: "OpenClaw skills, plugins, and skill folders are supply-chain risk and must be treated as trusted or untrusted code accordingly.",
    status: "verified",
    note: "OpenClaw security docs explicitly warn that plugin and skill code is a trust boundary.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openclaw-security", "openclaw-secrets"],
  },
  {
    id: "anchor-14",
    anchor: "OpenClaw current docs expose strict config requirements, additive SecretRefs, and a first-class PDF tool.",
    status: "verified",
    note: "Current configuration, secrets, and PDF docs confirm all three.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openclaw-configuration", "openclaw-secrets", "openclaw-pdf"],
  },
  {
    id: "anchor-15",
    anchor: "OpenClaw can use a managed browser, attached Chrome relay, and remote nodes; headless mode can trigger more anti-bot friction.",
    status: "verified",
    note: "Browser docs, login docs, node docs, and FAQ together describe the browser fabric tradeoffs.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openclaw-browser", "openclaw-browser-login", "openclaw-nodes", "openclaw-faq"],
  },
  {
    id: "anchor-16",
    anchor: "Automated self-update is possible but not the primary recommended operating pattern.",
    status: "verified",
    note: "The FAQ explicitly says self-update is possible but not the preferred baseline.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["openclaw-faq"],
  },
  {
    id: "anchor-17",
    anchor: "Wise personal tokens and OAuth 2.0 support different automation realities, and EU or UK PSD2 rules constrain some personal-token actions.",
    status: "verified",
    note: "Wise docs distinguish personal-token and OAuth patterns and call out PSD2 limits.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["wise-security-access", "wise-personal-tokens", "wise-getting-started"],
  },
  {
    id: "anchor-18",
    anchor: "Steel Cloud and Steel Local differ materially; auth-sensitive credential injection is not a safe assumption in Steel Local.",
    status: "verified",
    note: "Current Steel docs separate Cloud and Local and document credential features separately.",
    checkedAt: "2026-03-07T00:00:00.000Z",
    sourceIds: ["steel-sessions-overview", "steel-profiles", "steel-credentials", "steel-local-vs-cloud"],
  },
];
