import type { AnchorVerification, SourceRecord } from "./types.js";

export const OFFICIAL_SOURCES: SourceRecord[] = [
  {
    id: "openai-gpt-5.4-model",
    label: "OpenAI GPT-5.4 model page",
    domain: "openai",
    url: "https://developers.openai.com/api/docs/models/gpt-5.4",
    purpose: "Verify GPT-5.4 status, context window, and reasoning controls.",
  },
  {
    id: "openai-chatgpt-gpt-5.4",
    label: "OpenAI Help: GPT-5.3 and GPT-5.4 in ChatGPT",
    domain: "openai",
    url: "https://help.openai.com/en/articles/11909943-gpt-52-in-chatgpt",
    purpose: "Verify current ChatGPT model availability and GPT-5.4 positioning.",
  },
  {
    id: "openai-pro-plan",
    label: "OpenAI Help: ChatGPT Pro",
    domain: "openai",
    url: "https://help.openai.com/en/articles/9793128-what-is-chatgpt-pro",
    purpose: "Verify Pro plan unlimited GPT-5 access guardrails.",
  },
  {
    id: "openai-business-limits",
    label: "OpenAI Help: ChatGPT Business models and limits",
    domain: "openai",
    url: "https://help.openai.com/en/articles/12003714-chatgpt-business-models-limits",
    purpose: "Verify Business plan limits and current default ChatGPT models.",
  },
  {
    id: "openai-codex-plan",
    label: "OpenAI Help: Using Codex with your ChatGPT plan",
    domain: "openai",
    url: "https://help.openai.com/en/articles/11369540-using-codex-with-your-chatgpt-plan",
    purpose: "Verify Codex sign-in, client surfaces, and plan-based usage windows.",
  },
  {
    id: "openai-codex-upgrades",
    label: "OpenAI blog: Introducing upgrades to Codex",
    domain: "openai",
    url: "https://openai.com/index/introducing-upgrades-to-codex/",
    purpose: "Verify Codex availability surfaces and GPT-5-Codex rollout.",
  },
  {
    id: "openai-codex-app",
    label: "OpenAI blog: Introducing the Codex app",
    domain: "openai",
    url: "https://openai.com/index/introducing-the-codex-app/",
    purpose: "Verify app availability, Windows support, and continuous background automation direction.",
  },
  {
    id: "openai-gpt-5.3-codex",
    label: "OpenAI blog: Introducing GPT-5.3-Codex",
    domain: "openai",
    url: "https://openai.com/index/introducing-gpt-5-3-codex/",
    purpose: "Verify the strongest currently documented Codex-native model.",
  },
  {
    id: "openai-model-release-notes",
    label: "OpenAI Help: Model release notes",
    domain: "openai",
    url: "https://help.openai.com/en/articles/9624314-model-release-notes",
    purpose: "Verify GPT-4.5 preview deprecation and Codex model notes.",
  },
  {
    id: "openclaw-model-providers",
    label: "OpenClaw docs: Model providers",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/concepts/model-providers",
    purpose: "Verify OpenAI Codex OAuth support and documented provider/model refs.",
  },
  {
    id: "openclaw-multi-agent",
    label: "OpenClaw docs: Multi-agent routing",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/concepts/multi-agent",
    purpose: "Verify per-agent isolation, workspaces, and agentDir behavior.",
  },
  {
    id: "openclaw-multiple-gateways",
    label: "OpenClaw docs: Multiple gateways",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/gateway/multiple-gateways",
    purpose: "Verify single-gateway guidance and isolation requirements.",
  },
  {
    id: "openclaw-cron-vs-heartbeat",
    label: "OpenClaw docs: Cron vs Heartbeat",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/automation/cron-vs-heartbeat",
    purpose: "Verify how heartbeat and cron should be combined.",
  },
  {
    id: "openclaw-memory",
    label: "OpenClaw docs: Memory",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/concepts/memory",
    purpose: "Verify Markdown memory, QMD support, and embedding limitations under Codex OAuth.",
  },
  {
    id: "openclaw-browser",
    label: "OpenClaw docs: Browser",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/tools/browser",
    purpose: "Verify managed browser, extension relay, and headless support.",
  },
  {
    id: "openclaw-browser-login",
    label: "OpenClaw docs: Browser login",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/tools/browser-login",
    purpose: "Verify attached/manual-login guidance for authenticated sites.",
  },
  {
    id: "openclaw-configuration",
    label: "OpenClaw docs: Configuration",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/gateway/configuration",
    purpose: "Verify strict config validation behavior.",
  },
  {
    id: "openclaw-secrets",
    label: "OpenClaw docs: Secrets management",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/gateway/secrets",
    purpose: "Verify SecretRef coverage and supported secret-bearing fields.",
  },
  {
    id: "openclaw-pdf",
    label: "OpenClaw docs: PDF tool",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/tools/pdf",
    purpose: "Verify first-class PDF tool availability.",
  },
  {
    id: "openclaw-security",
    label: "OpenClaw docs: Security",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/gateway/security",
    purpose: "Verify skills, plugins, and trusted-code warnings.",
  },
  {
    id: "openclaw-faq",
    label: "OpenClaw docs: FAQ",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/help/faq",
    purpose: "Verify headless browser tradeoffs and update automation guidance.",
  },
  {
    id: "openclaw-cli",
    label: "OpenClaw docs: CLI reference",
    domain: "openclaw",
    url: "https://docs.openclaw.ai/cli",
    purpose: "Verify Node runtime guidance and CLI commands for gateway install and status.",
  },
  {
    id: "wise-security-access",
    label: "Wise docs: Security & Access",
    domain: "wise",
    url: "https://docs.wise.com/api-docs/features/authentication-access/personal-tokens",
    purpose: "Verify personal-token and OAuth 2.0 auth split plus PSD2 limitations.",
  },
  {
    id: "wise-personal-tokens",
    label: "Wise docs: Personal Tokens",
    domain: "wise",
    url: "https://docs.wise.com/api-docs/guides/personal-tokens",
    purpose: "Verify personal-token restrictions for EU/UK users.",
  },
  {
    id: "wise-getting-started",
    label: "Wise docs: Getting started",
    domain: "wise",
    url: "https://docs.wise.com/guides/developer",
    purpose: "Verify partner-credential expectations and auth guidance.",
  },
];

export const DEFAULT_ANCHOR_VERIFICATIONS: AnchorVerification[] = [
  {
    id: "anchor-1",
    anchor: "ChatGPT Pro and Business unlimited GPT-5 access in ChatGPT is guardrail-based rather than truly uncapped.",
    status: "verified",
    note: "Official Help Center docs confirm unlimited or virtually unlimited GPT-5 access with abuse guardrails.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openai-pro-plan", "openai-business-limits"],
  },
  {
    id: "anchor-2",
    anchor: "GPT-5.4 is the current frontier model for professional work with a 1,050,000 token context window.",
    status: "verified",
    note: "The OpenAI API model page explicitly labels GPT-5.4 as the frontier model and documents the 1.05M context window.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openai-gpt-5.4-model"],
  },
  {
    id: "anchor-3",
    anchor: "GPT-5.4 is available everywhere you use Codex.",
    status: "drifted",
    note: "Current official Codex docs still center GPT-5-Codex and GPT-5.3-Codex on Codex surfaces. GPT-5.4 is documented in ChatGPT/API, but not as the universal Codex default.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openai-codex-upgrades", "openai-gpt-5.3-codex", "openai-gpt-5.4-model"],
  },
  {
    id: "anchor-4",
    anchor: "Codex-native frontier work currently rides on GPT-5.3-Codex or GPT-5-Codex rather than a public GPT-5.4 Codex release.",
    status: "verified",
    note: "The strongest current Codex-native model publicly documented by OpenAI is GPT-5.3-Codex, with GPT-5.4 documented separately for ChatGPT/API reasoning work.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openai-gpt-5.3-codex", "openai-gpt-5.4-model"],
  },
  {
    id: "anchor-5",
    anchor: "Codex supports ChatGPT sign-in and is included with ChatGPT plans.",
    status: "verified",
    note: "OpenAI Help and blog docs explicitly describe signing in with ChatGPT and included plan access.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openai-codex-plan", "openai-codex-upgrades"],
  },
  {
    id: "anchor-6",
    anchor: "Current Codex Pro local usage windows are higher than the prompt's 223-1120 estimate.",
    status: "drifted",
    note: "The current official plan article documents roughly 300-1,500 local Pro messages per 5 hours, with task-size variance and a shared weekly limit.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openai-codex-plan"],
  },
  {
    id: "anchor-7",
    anchor: "OpenClaw officially supports Codex OAuth / ChatGPT sign-in.",
    status: "verified",
    note: "OpenClaw model provider docs explicitly support `openai-codex` OAuth for external tools and workflows.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openclaw-model-providers"],
  },
  {
    id: "anchor-8",
    anchor: "OpenClaw recommends Node runtime for stable gateways and does not recommend Bun for gateway installs.",
    status: "verified",
    note: "The CLI reference says gateway install defaults to Node runtime and specifically notes Bun is not recommended.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openclaw-cli"],
  },
  {
    id: "anchor-9",
    anchor: "The strongest always-on OpenClaw pattern is one primary gateway with remote nodes and clients.",
    status: "verified",
    note: "Multiple-gateway docs recommend one gateway for most setups, while FAQ/docs describe remote nodes and tailnet access for distributed control.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openclaw-multiple-gateways", "openclaw-faq"],
  },
  {
    id: "anchor-10",
    anchor: "Cron and heartbeat serve different purposes and should be combined.",
    status: "verified",
    note: "OpenClaw's Cron vs Heartbeat guide explicitly recommends using both together.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openclaw-cron-vs-heartbeat"],
  },
  {
    id: "anchor-11",
    anchor: "OpenClaw memory is Markdown-first, and Codex OAuth does not satisfy embeddings for memory search.",
    status: "verified",
    note: "The memory docs explicitly say Markdown files are the source of truth and Codex OAuth does not cover embeddings.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openclaw-memory"],
  },
  {
    id: "anchor-12",
    anchor: "OpenClaw supports QMD and local memory-search backends.",
    status: "verified",
    note: "The memory docs explicitly document the experimental QMD backend and local embedding mode.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openclaw-memory"],
  },
  {
    id: "anchor-13",
    anchor: "OpenClaw skills, plugins, and skill folders are supply-chain risk and must be treated as trusted or untrusted code accordingly.",
    status: "verified",
    note: "OpenClaw security and skills docs explicitly warn that plugins are trusted code and third-party skills should be treated as untrusted code.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openclaw-security", "openclaw-secrets"],
  },
  {
    id: "anchor-14",
    anchor: "OpenClaw current docs expose strict config validation, additive SecretRefs, and a first-class PDF tool.",
    status: "verified",
    note: "Current configuration, secrets, and PDF docs confirm all three. The exact command in docs is `openclaw doctor`, not a documented `openclaw config validate --json` entry.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openclaw-configuration", "openclaw-secrets", "openclaw-pdf"],
  },
  {
    id: "anchor-15",
    anchor: "OpenClaw can use a managed browser or an attached Chrome relay, and headless mode is more likely to trigger anti-bot checks.",
    status: "verified",
    note: "Browser docs cover the managed browser and extension relay; FAQ documents headless mode and anti-bot risk.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openclaw-browser", "openclaw-faq", "openclaw-browser-login"],
  },
  {
    id: "anchor-16",
    anchor: "Automated self-update is possible but not the primary recommended operating pattern.",
    status: "verified",
    note: "The FAQ explicitly says asking OpenClaw to update itself is possible but not recommended.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openclaw-faq"],
  },
  {
    id: "anchor-17",
    anchor: "Wise personal tokens and OAuth 2.0 support different automation realities, and EU/UK PSD2 constrains personal-token actions.",
    status: "verified",
    note: "Wise docs explicitly distinguish small-business personal tokens from partner OAuth 2.0 and call out EU/UK PSD2 limits.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["wise-security-access", "wise-personal-tokens", "wise-getting-started"],
  },
  {
    id: "anchor-18",
    anchor: "GPT-4.5-preview assumptions are stale and deprecated.",
    status: "verified",
    note: "OpenAI model docs and retirement notes show GPT-4.5 preview is deprecated while GPT-5.4 is current.",
    checkedAt: "2026-03-06T00:00:00.000Z",
    sourceIds: ["openai-model-release-notes", "openai-gpt-5.4-model"],
  },
];
